system_maintenance/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'system_maintenance'

urlpatterns = [
    path('', views.system_maintenance_home_view, name='system_maintenance_home_view'),
    path('authentication/', auth_views.LoginView.as_view(template_name='system_maintenance/authentication.html'), name='authentication'),
    path('documentation/', views.DocumentationRecordListView.as_view(), name='documentation_record_list'),
    path('documentation/<int:pk>/', views.DocumentationRecordDetailView.as_view(), name='documentation_record_detail'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/system_maintenance/'), name='logout'),
    path('raw/<type_of_record>/<type_of_field>/<int:record_pk>/', views.raw_view, name='raw_view'),
    path('records/', views.MaintenanceRecordListView.as_view(), name='maintenance_record_list'),
    path('records/<int:pk>/', views.MaintenanceRecordDetailView.as_view(), name='maintenance_record_detail'),
]

system_maintenance/templates/system_maintenance/_documentation_record_list_item.html
<a href="{% url 'system_maintenance:documentation_record_detail' record.pk %}" class="list-group-item">
  <h5>
    {{ record.title }}
    <small>
      - {{ record.maintenance_type }}
      <br>Created: {{ record.created_at }}
      {% if record.created_at|date:'r' != record.updated_at|date:'r' %}
        <br>Updated: {{ record.updated_at }}
      {% endif %}
    </small>
  </h5>
</a>

system_maintenance/templates/system_maintenance/_maintenance_record_list_item.html
<a href="{% url 'system_maintenance:maintenance_record_detail' record.pk %}" class="list-group-item
  {% if record.status == 'In Progress' %}list-group-item-warning{% endif %}
  {% if record.status == 'Failed' %}list-group-item-danger{% endif %}
">
    {{ record.datetime|date:'Y-m-d' }} - <strong>{{ record.system }}</strong> - {{ record.maintenance_type }} by {{ record.sys_admin }}

    {% if record.hardware.count %}
      - {{ record.hardware.all|join:', ' }}
    {% endif %}

    {% if record.software.count %}
      - {{ record.software.all|join:', ' }}
    {% endif %}
</a>

system_maintenance/templates/system_maintenance/_panel.html
<a name="{{ type_of_field }}"></a>
<div class="panel panel-{{ panel_type }}">

  <div class="panel-heading">
    <h1 class="panel-title">
      <a href='#summary'>{{ type_of_field|title }}</a>
      <small class="pull-right"><a href="{% url 'system_maintenance:raw_view' type_of_record=type_of_record record_pk=record_pk type_of_field=type_of_field %}" target="_blank">View raw {{ markup_type }}</a></small>
    </h1>
  </div>

  <div class="panel-body">
    {{ content }}
  </div>

  <a href="#{{ type_of_field }}">
    <div class="panel-footer panel-{{ panel_type }}"></div>
  </a>

</div>

system_maintenance/templates/system_maintenance/_related_records_button.html
{% if record_count %}
  {% with singular_suffix|add:","|add:plural_suffix as pluralize_rule %}
    <a class="btn btn-info btn-lg full-width-on-mobile" href="#{{ anchor }}" role="button">
      <span class="hide-on-mobile">{{ record_count }}</span>
      {{ label }}<span class="show-on-mobile-inline">{{ plural_suffix }}</span><span class="hide-on-mobile">{{ record_count|pluralize:pluralize_rule }}</span>
    </a>
  {% endwith %}
{% endif %}

system_maintenance/templates/system_maintenance/_summary_button.html
{% load humanize %}

{% with singular_suffix|add:","|add:plural_suffix as pluralize_rule %}

  {# Non-Mobile: show button group with counts and link to admin #}
  <div class="btn-group btn-group-lg hide-on-mobile" role="group" aria-label="...">
    <a class="btn btn-{{ btn_type }}" href="{% if list_url %}{% url list_url %}{% else %}#{% endif %}" role="button">
      {{ list_count|intcomma }} {{ label }}{{ list_count|pluralize:pluralize_rule }}
    </a>
    {% if user.is_staff %}
      <a class="btn btn-{{ btn_type }}" href="{% url admin_url %}" target="_blank" role="button">
        <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
      </a>
    {% endif %}
  </div>

  {# Mobile: show simplified full-width button #}
  <a class="btn btn-{{ btn_type }} btn-lg full-width-on-mobile show-on-mobile-block" href="{% if list_url %}{% url list_url %}{% else %}#{% endif %}" role="button">{{ label|add:plural_suffix }}</a>

{% endwith %}

system_maintenance/templates/system_maintenance/authentication.html
{% extends "system_maintenance/base.html" %}

{% block title %}System Maintenance{% endblock %}

{% block content %}

  <div class="container">

    {% if not user.is_authenticated %}

      <div class="row">
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger alert-dismissible col-sm-offset-2 col-sm-8" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{ error }}
          </div>
        {% endfor %}
      </div>

      <h1 class="text-center">SysAdmin Authentication</h1>
      <hr>

      <form class="form-horizontal" role="form" action="{% url 'system_maintenance:authentication' %}?next={% if request.GET.next %}{{ request.GET.next }}{% else %}{% url 'system_maintenance:system_maintenance_home_view' %}{% endif %}" method="post">
        {% csrf_token %}

        <div class="form-group {% if form.username.errors %}has-error{% endif %}">
          <label class="control-label col-sm-offset-2 col-sm-2 hidden-xs" for="id_username">Username:</label>
          <div class="col-sm-4">
            <input id="id_username" class="form-control" maxlength="254" name="username" type="text" placeholder="Enter username" autofocus>
            {% for error in form.username.errors %}
              <span class="help-block">{{ error }}</span>
            {% endfor %}
          </div>
        </div>

        <div class="form-group {% if form.password.errors %}has-error{% endif %}">
          <label class="control-label col-sm-offset-2 col-sm-2 hidden-xs" for="id_password">Password:</label>
          <div class="col-sm-4">
            <input id="id_password" class="form-control" name="password" type="password" placeholder="Enter password">
            {% for error in form.password.errors %}
              <span class="help-block">{{ error }}</span>
            {% endfor %}
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-4 col-sm-4">
            <button type="submit" class="btn btn-primary" style="width:100%">Login</button>
          </div>
        </div>

      </form>

    {% else %}

      <h1>Access denied.</h1>

      {% if not user.is_active %}
        <p>Hello {{ user.first_name|default:user }}. Your account is inactive.</p>
      {% else %}
        <p>Hello {{ user.first_name|default:user }}. You are not a system administrator.</p>
      {% endif %}

      <input class="btn btn-default" value="Previous Page" onClick="javascript:history.go(-1);">
      <a class="btn btn-default" href="{% url 'system_maintenance:logout' %}?next={{ request.GET.next }}">Logout</a>

    {% endif %}

  </div>

{% endblock content %}

system_maintenance/templates/system_maintenance/documentation_record_detail.html
{% extends "system_maintenance/base.html" %}
{% load project_home %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
  <div class='container'>

    <ol class="breadcrumb">
      {% project_home_breadcrumb_bs3 %}
      <li><a href="{% url 'system_maintenance:system_maintenance_home_view' %}">System Maintenance</a></li>
      <li><a href="{% url 'system_maintenance:documentation_record_list' %}">Documentation Records</a></li>
      <li class="active">{{ object }}</li>
    </ol>

    <a name='summary'></a>
    <div class="jumbotron">
      <h1>{{ object.title }}</h1>
      <p><strong>Type:</strong> {{ object.maintenance_type }}</p>
      <p><strong>Created:</strong> {{ object.created_at }}</p>
      {% if object.created_at|date:'r' != object.updated_at|date:'r' %}
        <p><strong>Updated:</strong> {{ object.updated_at }}</p>
      {% endif %}

      {% if object.documentation.raw %}
        <a class="btn btn-info btn-lg full-width-on-mobile" href="#documentation" role="button">Documentation</a>
      {% endif %}

      {% include "system_maintenance/_related_records_button.html" with label="Maintenance Record" record_count=object.maintenance_records.count anchor="maintenance-records" singular_suffix="" plural_suffix="s" %}

      {% if user.is_staff %}
        <a class="btn btn-primary btn-lg full-width-on-mobile" href="{% url 'admin:system_maintenance_documentationrecord_change' object.id %}" target="_blank" role="button">
          <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
        </a>
      {% endif %}

    </div>

    {% if object.documentation.raw %}
      {% with type_of_record='documentation' record_pk=object.pk type_of_field='documentation' markup_type=object.documentation.markup_type panel_type='info' content=object.documentation %}
        {% include "system_maintenance/_panel.html" %}
      {% endwith %}
    {% endif %}

    {% if object.maintenance_records.count %}
      <a name='maintenance-records'></a>
      <div class="panel panel-info">

        <div class="panel-heading">
          <h1 class="panel-title"><a href='#summary'>Related Maintenance Records</a></h1>
        </div>

        <div class="panel-body">

          <div class="list-group">
            {% for record in object.maintenance_records.all %}
              {% include "system_maintenance/_maintenance_record_list_item.html" %}
            {% endfor %}
          </div>

        </div>

        <a href='#maintenance-records'>
          <div class="panel-footer panel-info"></div>
        </a>

      </div>
    {% endif %}

  </div>
{% endblock content %}

system_maintenance/templates/system_maintenance/documentation_record_list.html
{% extends "system_maintenance/base.html" %}
{% load project_home %}

{% block title %}Documentation Records{% endblock %}

{% block content %}
  <div class='container'>

    <ol class="breadcrumb">
      {% project_home_breadcrumb_bs3 %}
      <li><a href="{% url 'system_maintenance:system_maintenance_home_view' %}">System Maintenance</a></li>
      <li class="active">Documentation Records</li>
    </ol>

    <div class="jumbotron">
      <h1>Documentation Records</h1>
    </div>

    <div class="list-group">
      {% for record in object_list %}
        {% include "system_maintenance/_documentation_record_list_item.html" %}
      {% endfor %}
    </div>

    {% include "system_maintenance/_pagination.html" %}

  </div>
{% endblock content %}

system_maintenance/templates/system_maintenance/maintenance_detail.html
<!DOCTYPE html>
<html>
<head>
  <title>{{ object.system }} {{ object.datetime|date:'Y-m-d' }}</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <style>
    .codehilite .hll { background-color: #ffffcc }
    .codehilite .c { color: #999988; font-style: italic } /* Comment */
    .codehilite .err { color: #a61717; background-color: #e3d2d2 } /* Error */
    .codehilite .k { color: #000000; font-weight: bold } /* Keyword */
    .codehilite .o { color: #000000; font-weight: bold } /* Operator */
    .codehilite .cm { color: #999988; font-style: italic } /* Comment.Multiline */
    .codehilite .cp { color: #999999; font-weight: bold; font-style: italic } /* Comment.Preproc */
    .codehilite .c1 { color: #999988; font-style: italic } /* Comment.Single */
    .codehilite .cs { color: #999999; font-weight: bold; font-style: italic } /* Comment.Special */
    .codehilite .gd { color: #000000; background-color: #ffdddd } /* Generic.Deleted */
    .codehilite .ge { color: #000000; font-style: italic } /* Generic.Emph */
    .codehilite .gr { color: #aa0000 } /* Generic.Error */
    .codehilite .gh { color: #999999 } /* Generic.Heading */
    .codehilite .gi { color: #000000; background-color: #ddffdd } /* Generic.Inserted */
    .codehilite .go { color: #888888 } /* Generic.Output */
    .codehilite .gp { color: #555555 } /* Generic.Prompt */
    .codehilite .gs { font-weight: bold } /* Generic.Strong */
    .codehilite .gu { color: #aaaaaa } /* Generic.Subheading */
    .codehilite .gt { color: #aa0000 } /* Generic.Traceback */
    .codehilite .kc { color: #000000; font-weight: bold } /* Keyword.Constant */
    .codehilite .kd { color: #000000; font-weight: bold } /* Keyword.Declaration */
    .codehilite .kn { color: #000000; font-weight: bold } /* Keyword.Namespace */
    .codehilite .kp { color: #000000; font-weight: bold } /* Keyword.Pseudo */
    .codehilite .kr { color: #000000; font-weight: bold } /* Keyword.Reserved */
    .codehilite .kt { color: #445588; font-weight: bold } /* Keyword.Type */
    .codehilite .m { color: #009999 } /* Literal.Number */
    .codehilite .s { color: #d01040 } /* Literal.String */
    .codehilite .na { color: #008080 } /* Name.Attribute */
    .codehilite .nb { color: #0086B3 } /* Name.Builtin */
    .codehilite .nc { color: #445588; font-weight: bold } /* Name.Class */
    .codehilite .no { color: #008080 } /* Name.Constant */
    .codehilite .nd { color: #3c5d5d; font-weight: bold } /* Name.Decorator */
    .codehilite .ni { color: #800080 } /* Name.Entity */
    .codehilite .ne { color: #990000; font-weight: bold } /* Name.Exception */
    .codehilite .nf { color: #990000; font-weight: bold } /* Name.Function */
    .codehilite .nl { color: #990000; font-weight: bold } /* Name.Label */
    .codehilite .nn { color: #555555 } /* Name.Namespace */
    .codehilite .nt { color: #000080 } /* Name.Tag */
    .codehilite .nv { color: #008080 } /* Name.Variable */
    .codehilite .ow { color: #000000; font-weight: bold } /* Operator.Word */
    .codehilite .w { color: #bbbbbb } /* Text.Whitespace */
    .codehilite .mf { color: #009999 } /* Literal.Number.Float */
    .codehilite .mh { color: #009999 } /* Literal.Number.Hex */
    .codehilite .mi { color: #009999 } /* Literal.Number.Integer */
    .codehilite .mo { color: #009999 } /* Literal.Number.Oct */
    .codehilite .sb { color: #d01040 } /* Literal.String.Backtick */
    .codehilite .sc { color: #d01040 } /* Literal.String.Char */
    .codehilite .sd { color: #d01040 } /* Literal.String.Doc */
    .codehilite .s2 { color: #d01040 } /* Literal.String.Double */
    .codehilite .se { color: #d01040 } /* Literal.String.Escape */
    .codehilite .sh { color: #d01040 } /* Literal.String.Heredoc */
    .codehilite .si { color: #d01040 } /* Literal.String.Interpol */
    .codehilite .sx { color: #d01040 } /* Literal.String.Other */
    .codehilite .sr { color: #009926 } /* Literal.String.Regex */
    .codehilite .s1 { color: #d01040 } /* Literal.String.Single */
    .codehilite .ss { color: #990073 } /* Literal.String.Symbol */
    .codehilite .bp { color: #999999 } /* Name.Builtin.Pseudo */
    .codehilite .vc { color: #008080 } /* Name.Variable.Class */
    .codehilite .vg { color: #008080 } /* Name.Variable.Global */
    .codehilite .vi { color: #008080 } /* Name.Variable.Instance */
    .codehilite .il { color: #009999 } /* Literal.Number.Integer.Long */
  </style>
</head>

<body>
<br>
<br>
<br>
  <div class='container'>

    <a name='summary'></a>
    <div class="jumbotron
      {% if object.status == 'In Progress' %}alert-warning{% endif %}
      {% if object.status == 'Failed' %}alert-danger{% endif %}
    ">
      <h1>{{ object.system }} <small>{{ object.datetime.date }}</small></h1>
      <p><strong>Type:</strong> {{ object.maintenance_type }}</p>
      <p><strong>Who:</strong> {{ object.sys_admin }}</p>

      {% if object.hardware.count == 1 %}
        <p><strong>Hardware:</strong> {{ object.hardware.first }}</p>
      {% elif object.hardware.count > 1 %}
        <p><strong>Hardware:</strong></p>
        <ul>
          {% for hardware in object.hardware.all %}
            <li>{{ hardware }}</li>
          {% endfor %}
        </ul>
      {% endif %}

      {% if object.software.count == 1 %}
        <p><strong>Software:</strong> {{ object.software.first }}</p>
      {% elif object.software.count > 1 %}
        <p><strong>Software:</strong></p>
        <ul>
          {% for software in object.software.all %}
            <li>{{ software }}</li>
          {% endfor %}
        </ul>
      {% endif %}

      <p><strong>Status:</strong> {{ object.status }}</p>

      <p>
        {% if object.description.raw %}
          <a class="btn btn-info btn-lg" href="#description" role="button">Description</a>
        {% endif %}

        {% if object.procedure.raw %}
          <a class="btn btn-success btn-lg" href="#procedure" role="button">Procedure</a>
        {% endif %}

        {% if object.problems.raw %}
          <a class="btn btn-danger btn-lg" href="#problems" role="button">Problems</a>
        {% endif %}

        {% with object.referenced_records.count|add:object.referencing_records.count as related_record_count %}
          {% if related_record_count %}
            <a class="btn btn-info btn-lg" href="#related-records" role="button">
              {{ related_record_count }} Related Record{{ related_record_count|pluralize }}
            </a>
          {% endif %}
        {% endwith %}

        {% if user.is_staff %}
          <a class="btn btn-primary btn-lg" href="{% url 'admin:system_maintenance_maintenance_change' object.id %}" target="_blank" role="button">
            <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
          </a>
        {% endif %}
      </p>

    </div>

    {% if object.description.raw %}
      <a name='description'></a>
      <div class="panel panel-info">

        <div class="panel-heading">
          <h1 class="panel-title"><a href='#summary'>Description</a></h1>
        </div>

        <div class="panel-body">
          {{ object.description }}
        </div>

        <a href='#description'>
          <div class="panel-footer panel-info" style="background-color: #d9edf7;"></div>
        </a>

      </div>
    {% endif %}

    {% if object.procedure.raw %}
      <a name='procedure'></a>
      <div class="panel panel-success">

        <div class="panel-heading">
          <h1 class="panel-title"><a href='#summary'>Procedure</a></h1>
        </div>

        <div class="panel-body">
          {{ object.procedure }}
        </div>

        <a href='#procedure'>
          <div class="panel-footer panel-success" style="background-color: #dff0d8;"></div>
        </a>

      </div>
    {% endif %}

    {% if object.problems.raw %}
      <a name='problems'></a>
      <div class="panel panel-danger">

        <div class="panel-heading">
          <h1 class="panel-title"><a href='#summary'>Problems</a></h1>
        </div>

        <div class="panel-body">
          {{ object.problems }}
        </div>

        <a href='#problems'>
          <div class="panel-footer panel-danger" style="background-color: #f2dede;"></div>
        </a>

      </div>
    {% endif %}

    {% if object.referenced_records.count or object.referencing_records.count %}
      <a name='related-records'></a>
      <div class="panel panel-info">

        <div class="panel-heading">
          <h1 class="panel-title"><a href='#summary'>Related Records</a></h1>
        </div>

        <div class="panel-body">

          {% if object.referenced_records.count %}
            <h4>See also:</h4>
            <div class="list-group">
              {% for record in object.referenced_records.all %}
                {% include "system_maintenance/_maintenance_record_list_item.html" %}
              {% endfor %}
            </div>
          {% endif %}

          {% if object.referencing_records.count %}
            <h4>Referenced by:</h4>
            <div class="list-group">
              {% for record in object.referencing_records.all %}
                {% include "system_maintenance/_maintenance_record_list_item.html" %}
              {% endfor %}
            </div>
          {% endif %}

        </div>

        <a href='#related-records'>
          <div class="panel-footer panel-info" style="background-color: #d9edf7;"></div>
        </a>

      </div>
    {% endif %}

  </div>
  <br>
  <br>
  <br>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</body>
</html>

system_maintenance/templates/system_maintenance/maintenance_list.html
<!DOCTYPE html>
<html>
<head>
  <title>Maintenance Records</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
</head>

<body>
<br>
<br>
<br>
  <div class='container'>

    <h1>Maintenance Records</h1>
    <div class="list-group">
      {% for record in object_list %}
        {% include "system_maintenance/_maintenance_record_list_item.html" %}
      {% endfor %}
    </div>

  </div>
  <br>
  <br>
  <br>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</body>
</html>

system_maintenance/templates/system_maintenance/maintenance_record_detail.html
{% extends "system_maintenance/base.html" %}
{% load project_home %}

{% block title %}{{ object.system }} {{ object.datetime|date:'Y-m-d' }}{% endblock %}

  {# I think I want who/when changed #}
  {# Change list decorator #}
  {# PROBABLY NOT, BECAUSE CHANGES HEIGHT OF FOOTER: On hover show up arrows on panel footer #}
  {# PROBABLY NOT, BECAUSE CHANGES COLOR OF H1: Make entire panel header into link to summary? If so, show on hover? #}
{% block content %}
  <div class='container'>

    <ol class="breadcrumb">
      {% project_home_breadcrumb_bs3 %}
      <li><a href="{% url 'system_maintenance:system_maintenance_home_view' %}">System Maintenance</a></li>
      <li><a href="{% url 'system_maintenance:maintenance_record_list' %}">Maintenance Records</a></li>
      <li class="active">{{ object }}</li>
    </ol>

    <a name='summary'></a>
    <div class="jumbotron
      {% if object.status == 'In Progress' %}alert-warning{% endif %}
      {% if object.status == 'Failed' %}alert-danger{% endif %}
    ">
      <h1>{{ object.system }} <small>{{ object.datetime.date }}</small></h1>
      <p><strong>Type:</strong> {{ object.maintenance_type }}</p>
      <p><strong>Who:</strong> {{ object.sys_admin }}</p>

      {% if object.hardware.count == 1 %}
        <p><strong>Hardware:</strong> {{ object.hardware.first }}</p>
      {% elif object.hardware.count > 1 %}
        <p><strong>Hardware:</strong></p>
        <ul>
          {% for hardware in object.hardware.all %}
            <li>{{ hardware }}</li>
          {% endfor %}
        </ul>
      {% endif %}

      {% if object.software.count == 1 %}
        <p><strong>Software:</strong> {{ object.software.first }}</p>
      {% elif object.software.count > 1 %}
        <p><strong>Software:</strong></p>
        <ul>
          {% for software in object.software.all %}
            <li>{{ software }}</li>
          {% endfor %}
        </ul>
      {% endif %}

      <p><strong>Status:</strong> {{ object.status }}</p>

      {% if object.description.raw %}
        <a class="btn btn-info btn-lg full-width-on-mobile" href="#description" role="button">Description</a>
      {% endif %}

      {% if object.procedure.raw %}
        <a class="btn btn-success btn-lg full-width-on-mobile" href="#procedure" role="button">Procedure</a>
      {% endif %}

      {% if object.problems.raw %}
        <a class="btn btn-danger btn-lg full-width-on-mobile" href="#problems" role="button">Problems</a>
      {% endif %}

      {% include "system_maintenance/_related_records_button.html" with label="Related Document" record_count=object.documentation_records.count anchor="document-records" singular_suffix="" plural_suffix="s" %}

      {% include "system_maintenance/_related_records_button.html" with label="Related Record" record_count=object.referenced_records.count|add:object.referencing_records.count anchor="related-records" singular_suffix="" plural_suffix="s" %}

      {% if user.is_staff %}
        <a class="btn btn-primary btn-lg full-width-on-mobile" href="{% url 'admin:system_maintenance_maintenancerecord_change' object.id %}" target="_blank" role="button">
          <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
        </a>
      {% endif %}

    </div>

    {% if object.description.raw %}
      {% with type_of_record='maintenance' record_pk=object.pk type_of_field='description' markup_type=object.description.markup_type panel_type='info' content=object.description %}
        {% include "system_maintenance/_panel.html" %}
      {% endwith %}
    {% endif %}

    {% if object.procedure.raw %}
      {% with type_of_record='maintenance' record_pk=object.pk type_of_field='procedure' markup_type=object.procedure.markup_type panel_type='success' content=object.procedure %}
        {% include "system_maintenance/_panel.html" %}
      {% endwith %}
    {% endif %}

    {% if object.problems.raw %}
      {% with type_of_record='maintenance' record_pk=object.pk type_of_field='problems' markup_type=object.problems.markup_type panel_type='danger' content=object.problems %}
        {% include "system_maintenance/_panel.html" %}
      {% endwith %}
    {% endif %}

    {% if object.documentation_records.count %}
      <a name='document-records'></a>
      <div class="panel panel-info">

        <div class="panel-heading">
          <h1 class="panel-title"><a href='#summary'>Relevant Documents</a></h1>
        </div>

        <div class="panel-body">
          <div class="list-group">
            {% for documentation in object.documentation_records.all %}

              <a href="{% url 'system_maintenance:documentation_record_detail' documentation.pk %}" class="list-group-item documentation-title">
                <h5>
                  {{ documentation.title }}
                  <small>- {{ documentation.category }}</small>
                  <br><small>Created: {{ documentation.created_at }}</small>
                  {% if documentation.created_at|date:'r' != documentation.updated_at|date:'r' %}
                    <br><small>Updated: {{ documentation.updated_at }}</small>
                  {% endif %}
                </h5>
              </a>

              <div class="list-group-item">
                <div class="container-fluid">
                  {{ documentation.documentation }}
                </div>
              </div>

            {% endfor %}
          </div>
        </div>

        <a href='#document-records'>
          <div class="panel-footer panel-info"></div>
        </a>

      </div>
    {% endif %}

    {% if object.referenced_records.count or object.referencing_records.count %}
      <a name='related-records'></a>
      <div class="panel panel-info">

        <div class="panel-heading">
          <h1 class="panel-title"><a href='#summary'>Related Records</a></h1>
        </div>

        <div class="panel-body">

          {% if object.referenced_records.count %}
            <h4>See also:</h4>
            <div class="list-group">
              {% for record in object.referenced_records.all %}
                {% include "system_maintenance/_maintenance_record_list_item.html" %}
              {% endfor %}
            </div>
          {% endif %}

          {% if object.referencing_records.count %}
            <h4>Referenced by:</h4>
            <div class="list-group">
              {% for record in object.referencing_records.all %}
                {% include "system_maintenance/_maintenance_record_list_item.html" %}
              {% endfor %}
            </div>
          {% endif %}

        </div>

        <a href='#related-records'>
          <div class="panel-footer panel-info"></div>
        </a>

      </div>
    {% endif %}

  </div>
{% endblock content %}

system_maintenance/templates/system_maintenance/maintenance_record_list.html
{% extends "system_maintenance/base.html" %}
{% load project_home %}

{% block title %}Maintenance Records{% endblock %}

{% block content %}
  <div class='container'>

    <ol class="breadcrumb">
      {% project_home_breadcrumb_bs3 %}
      <li><a href="{% url 'system_maintenance:system_maintenance_home_view' %}">System Maintenance</a></li>
      <li class="active">Maintenance Records</li>
    </ol>

    <div class="jumbotron">
      <h1>Maintenance Records</h1>
      <p>Background color indicates the status of the maintenance record:</p>
      <ul>
        <li>White: Complete</li>
        <li>Yellow: In Progress</li>
        <li>Red: Failed</li>
      </ul>
    </div>

    <div class="list-group">
      {% for record in object_list %}
        {% include "system_maintenance/_maintenance_record_list_item.html" %}
      {% endfor %}
    </div>

    {% include "system_maintenance/_pagination.html" %}

  </div>
{% endblock content %}

system_maintenance/templates/system_maintenance/raw.html
{% extends "system_maintenance/base.html" %}

{% block title %}raw {{ type_of_field }} | {{ record }}{% endblock %}

{% block content %}
  <div class='container'>
    <pre>{{ raw }}</pre>
  </div>
{% endblock content %}